### ISSUE TITLE
Add skeleton code

### ISSUE THREAD

**Issue by kimseongyu** [kakao-tech-campus-2nd-step3/Team28_Android#13]
## TODO LIST

- [x] Add skeletone code following clean architecture
- [x] Set login as starting point
- [ ] ~~Move Figma UI design to project~~

### Reference
[clean architecture](https://github.com/android10/Android-CleanArchitecture-Kotlin)
